### ISSUE TITLE
Jobs stuck in Eqw or hqw states

### ISSUE THREAD

**Issue by Amy-T** [wyim-pgl/DCBLAST#1]
Hi Dear Won Chol,

Thank you for developing DCBLAST.

Currently, we are trying to use DCBLAST to perform blastp on our Sun Grid Engine System.

The command we were using is:
perl dcblast.pl --ini configL.ini --input L6_Fv.faa --size 200 --output L6_Fv_vs_nr2 --blast blastp

We noticed that the .faa file was split successfully. However, the jobs were in Eqw or hqw states. Upon checking the error underlying Eqw state, we noticed that it is related to password entry error for the user ('can't get password entry for user "xxx". Either the user does not exist or NIS error!'); the user account is available on head node but not on the compute node. 

Hope you may be able to advise on how we can resolve the problem.

Thanks.

**Comment by ascendo** [comment]
Thank you for reporting.

Can you show me your INI file?

**Comment by ascendo** [comment]
Thank you for reporting.

Can you show me your INI file?

**Comment by wyim-pgl** [comment]
It looks like your computing nodes cannot access password system.

Usually,  you don't need to do anything special authenticate for SGE job submission, because if you already login to login node, SGE collect the your information from login node.

However, if the compute nodes are also under kerberos authenticate, then you will need to
enable security when you compile SGE, that is, add the -kerberos flag (and make sure you have the kerberos development libraries on the machine where you compile the source, etc)


Also these errors appear either consistently or inconsistently and are no longer correlated with the use of OpenDirectory (problems appear with local user accounts as well), NFS, case-insensitive filesystems or any other system settings.

More information and background on this issue can be found via these links

https://linuxfollies.blogspot.com/2014/05/sssd-setup-in-bright-cluster.html


Can you do qrsh or qsub for your job?

simple tests are below

```
qrsh hostname
```

```
 qsub -b y -t 1-40 hostname
```

or 

login as 'henry' instead of Henry.

If you have hetero HPC system with OSX and linux. It should be a problem.

If you cannot find anything, I hope you contact to your admin. Because this is not the DCBLAST problem.

**Comment by Amy-T** [comment]
Thanks for the suggestions. We will give it a try.
